spring:
  #zipkin服务端的地址
  zipkin:
    base-url: http://localhost:1000
  #rabbitmq的地址，它既不属于客户端，也不属于服务端，它是一个中间件
  rabbitmq:
    host: localhost
    #注意，5762是client登陆端口，15762是管理端口
    port: 5672
    username: ccx1016875161@126.com
    password: QTSS.a000
  sleuth:
    sampler:
      percentage: 1
  cloud:
    stream:
      bindings:
        input2:
          #所有设置了这个属性的实例都是消费组中的一个实例。我们发送
          #的消息会被所有destination相同的input通道所接收，那么设
          #置消费组的目的就是我们想要消息每次只被一个消息通道所接收，
          #而不是所有消息通道都接收。那么这些通道默认的策略是轮询接收。
          group: service
          destination: test
          consumer:
            #开启消息分区的功能
            partitioned: true
      #有多少消费者实例
      instance-count: 2
      #消费者实例的索引
      instance-index: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://one:1111/eureka/,http://two:1112/eureka/

server:
  port: 2341