spring:
  application:
    name: zuul-balance

eureka:
  client:
    serviceUrl:
      defaultZone: http://one:1111/eureka,http://two:1112/eureka

server:
  port: 8010

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  threadpool:
    pool1:
      coreSize: 5
    pool2:
      coreSize: 5